### ISSUE TITLE
BUG: /users matches /user

### ISSUE THREAD

**Issue by aaabramov** [unlockdmedia/stub-server#1]
Seems that [config example](https://github.com/unlockdmedia/stub-server/blob/master/scripts/example.yml):
```yml
- request:
    url: /user
  response:
    status: 200
    body: "hello"

- request:
    url: /users
  response:
    status: 200
    file: /scripts/users.json
```

has bug?

`curl -X GET http://localhost:8882/users` returns `hello` but should return `users.json` file content
